### ISSUE TITLE
为什么Piece-Square tables 是16*16的矩阵

### ISSUE THREAD

**Issue by sharpwood** [walker8088/moonfish#1]
为什么Piece-Square tables 是16 x 16的矩阵，棋盘只有9 x 10 
我看到sunfish的 Piece-Square tables 是 8 x 8 的 和棋盘大小相符。

**Comment by walker8088** [comment]
sunfish的矩阵要换算计算, 我借鉴了别的程序用的是16*16矩阵, 新版的已经改了,用13X14矩阵,这样红白互换的代码跟sunfish一样的,计算得分一次就能得到.

**Comment by sharpwood** [comment]
没太明白，不能用和棋盘大小一致的9X10的矩阵吗？ sunfish不是用的和国际象棋棋盘一样大的矩阵么？

**Comment by walker8088** [comment]
用超过棋盘大小的矩阵是为了马的快速走子合法性判断用的，moonfish有自己的考虑，认为这样效率会更高一些。
